backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->redirect(['adv/index']);
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Adv;
use common\models\News;
use common\models\User;
use frontend\models\ConfirmCodeForm;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Categories;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\widgets\ActiveForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'validate-login'],
                'rules' => [
                    [
                        'actions' => ['signup', 'login', 'validate-login', 'login-soc', 'shut-down'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionShutDown(){
        $this->layout = false;

        return $this->render('shutdown');
    }

    public function actionFavorite(){
        $items_id = Yii::$app->favorite->items();
        $model = Adv::find()->where(['id' => $items_id])->orderBy('date DESC')->all();

        return $this->render('favorite', compact('model'));
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex(){

        if($_SERVER['REQUEST_URI'] == '/en/')
            return $this->redirect('/', 301);

        $last_adv = Adv::findActive()->orderBy('date DESC')->limit(20)->all();
        $last_news = News::find()->where(['status' => News::STATUS_ACTIVE])->orderBy('date DESC')->limit(2)->all();
        return $this->render('index', compact( 'last_adv', 'last_news', 'categories'));
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if(!Yii::$app->user->isGuest) return $this->goBack(['site/index']);

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            return $this->goBack();
        } else {
            return $this->render('login', compact('model'));
        }


    }

    public function actionValidateLogin(){

        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            $model = new LoginForm(Yii::$app->getRequest()->getBodyParams()['LoginForm']);

            if (!$model->validate()) {
                return ActiveForm::validate($model);
            }
            else
                return [];
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goBack(['site/index']);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Signs user up.
     *
     * @return mixed
     * @throws \yii\base\Exception
     */
    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
//            \Yii::$app->response->format = Response::FORMAT_JSON;
            $model->sendEmail();
            Yii::$app->session->setFlash('success', Yii::t('app', 'Check your email and approve your registration'));
            return $this->goBack();
        } else {
            return $this->render('signup', compact('model'));
        }

    }

    public function actionValidateSignup()
    {
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            $model = new SignupForm(Yii::$app->getRequest()->getBodyParams()['SignupForm']);

            if (!$model->validate()) {
                return ActiveForm::validate($model);
            }
            else
                return [];
        }
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Подтверждение регистрации
     *
     * @param bool $token
     * @return string|Response
     * @throws NotFoundHttpException
     * @throws \yii\base\Exception
     */
    public function actionConfirm($token = false){

        if($token){
            $model = User::find()->where(['hash' => $token])->one();
            if(!$model) throw new NotFoundHttpException(Yii::t('app', 'User not found'));

            if($model->password != null){
                $model->hash = '';
                $model->success_email = true;
                $model->save();
                Yii::$app->session->setFlash('success', Yii::t('app', 'Your email address successfully confirmed'));
                return $this->redirect(['profile/settings']);
            }

            $model->setScenario('set_password');
            if($model->load(Yii::$app->request->post()) && $model->validate()){
                $model->setPassword($model->new_password);
                $model->hash = '';
                $model->success_email = true;
                $model->save();
                Yii::$app->user->login($model);
                Yii::$app->session->setFlash('warning', Yii::t('app', 'Please, fill your profile'));
                return $this->redirect(['profile/settings']);
            }
            return $this->render('confirm-set-password', compact('model'));
        }
        elseif (!$token){
            $model = new ConfirmCodeForm();

            if($model->load(Yii::$app->request->post()) && $model->validate())
                return $this->redirect(['confirm', 'token' => $model->token]);

            return $this->render('confirm-set-token', compact('model'));
        }
    }

    public function actionLoginSoc(){
        $s = file_get_contents('http://ulogin.ru/token.php?token=' . $_POST['token'] . '&host=' . $_SERVER['HTTP_HOST']);
        $user = json_decode($s, true);
        //$user['network'] - соц. сеть, через которую авторизовался пользователь
        //$user['identity'] - уникальная строка определяющая конкретного пользователя соц. сети
        //$user['first_name'] - имя пользователя
        //$user['last_name'] - фамилия пользователя

        $model = User::findByEmail($user['email']);

        if(!$model) {
            $model = new User();
            $model->email = $user['email'];
            $model->name  = $user['first_name'].' '.$user['last_name'];
            $model->success_email = true;
            $model->save();
        }
        Yii::$app->user->login($model);

        return $this->goBack();


    }

    public function actionTest(){

//        $this->layout = 'empty';
//        $user = User::findOne(7);
//        $this->layout = '@common/mail/layouts/html';
//        $body = $this->renderPartial('@common/mail/registration-confirm-html', compact('user'));
//        $ret = $this->render('@common/mail/_email_html', ['meta' => false, 'text' => $body, 'title' => Yii::t('app', 'Confirm registration')]);

//        return $ret;

        return $this->render('test');

    }
}

frontend/views/site/confirm-set-password.php
<?php
/**
 * Created by PhpStorm.
 * User: York
 * Date: 06.01.2018
 * Time: 12:06
 */
/* @var $this yii\web\View */
/* @var $model \common\models\User */
use yii\widgets\ActiveForm;


$this->title = Yii::t('app', 'Set password');
Yii::$app->breadcrumbs->Items([ $this->title]);

?>

<section class="content">
    <div class="col-sm-6 col-sm-push-3">
        <h1 class="margin-bottom-large"><?= $this->title?></h1>
        <?php $form = ActiveForm::begin([
            'id' => 'confirm-form'
        ]); ?>

        <?= $form->errorSummary($model)?>

        <?=$form->field($model, 'new_password')->passwordInput()?>
        <?=$form->field($model, 'new_password_repeat')->passwordInput()?>
        <div class="form-group">
            <?= \yii\helpers\Html::submitInput(Yii::t('app', 'Confirm'), ['class' => 'btn btn--green'])?>
        </div>
        <?php ActiveForm::end(); ?>

    </div>
    <div class="clearfix"></div>
</section>

frontend/views/site/confirm-set-token.php
<?php
/**
 * Created by PhpStorm.
 * User: York
 * Date: 06.01.2018
 * Time: 11:53
 */
/* @var $this yii\web\View */

use yii\widgets\ActiveForm;


$this->title = Yii::t('app', 'Confirm email address');
Yii::$app->breadcrumbs->Items([ $this->title]);

?>

<section class="content">


    <div class="col-sm-6 col-sm-push-3">
        <h1 class="margin-bottom-large"><?= $this->title?></h1>
        <?php $form = ActiveForm::begin([
            'id' => 'confirm-form'
        ]); ?>

        <?=$form->field($model, 'token')?>
        <div class="form-group">
            <?= \yii\helpers\Html::submitInput(Yii::t('app', 'Confirm'), ['class' => 'btn btn--green'])?>
        </div>
        <?php ActiveForm::end(); ?>

    </div>
    <div class="clearfix"></div>


</section>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;

$categories = \common\models\Categories::find()->where(['parent' => 0])->andWhere(['status' => true])->orderBy('position')->all();

?>
<section class="content site-error">

    <h1><?= Html::encode($this->title) ?></h1>
    <h3><?= nl2br(Html::encode($message)) ?></h3>
    
    <?=Yii::t('app', 'Use search or one of category below');?>

    <div class="row">
        <? $i = 0; foreach($categories as $category):?>
            <?= $i != 0 &&  $i % 6 == 0 ? '</div><div class="row">' : ''?>
            <div class="col-sm-4 col-md-2 col-xs-12">

                <h4><a href="<?= $category->link?>"><?= $category->name?></a></h4>

                <ul>
                    <?foreach($category->childs as $item):?>
                        <li><a href="<?= $item->link?>"><?= $item->name?></a></li>
                    <?endforeach?>
                </ul>
            </div>
        <?$i++; endforeach?>
    </div>

</section>

frontend/views/site/favorite.php
<?php
/**
 * Created by PhpStorm.
 * User: York
 * Date: 03.11.2017
 * Time: 17:36
 *
 * @var $this \yii\web\View
 * @var $model \common\models\Adv[]
 */

\Yii::$app->breadcrumbs->Items([
    Yii::t('app', 'Favorite')
]);
?>


<section class="content">

    <h1><?=Yii::t('app', 'Favorite');?> </h1>


    <div class="row">

        <?foreach ($model as $item):?>
            <div class="col-sm-3">
                <?=$this->render('//adv/catalog/_catalog-item!new', ['item' => $item])?>
            </div>
        <?endforeach;?>
    </div>
</section>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $last_news \common\models\News[] */
use common\models\CMS;
use yii\helpers\Html;

$this->title = 'Cyprus BAZAR';


?>



<?=$this->render('//common/main_category', compact('categories'))?>



<section class="newads-pricipaly">

    <div class="newads-principaly__title">
        <h2><?=Yii::t('app', 'New ads')?></h2>
        <a href="<?=\yii\helpers\Url::to(['adv/index'])?>"><span><?=Yii::t('app', 'All Ads')?></span> <img src="<?=Yii::getAlias('@dist')?>/img/more.svg" class='svg' alt="<?=Yii::t('app', 'All Ads')?>"> </a>
    </div>

    <div class="row hidden-mobile">
        <?foreach ($last_adv as $item):?>
            <div class="col-sm-3">
                <?=$this->render('//adv/catalog/_catalog-item!new', ['item' => $item])?>
            </div>
        <?endforeach;?>
    </div>

    <div class=" show-mobile owl-carousel owl-carousel-catalog catalog-items__main" style="height: 300px;">
        <?foreach ($last_adv as $item):?>
            <?=$this->render('//adv/catalog/_catalog-item!new', ['item' => $item])?>
        <?endforeach;?>
    </div>

</section>

<section class="index-image">
    <!--Index image Content  -->
    <div class="index-image__content">
        <!--Index image title  -->
        <div class="index-image__title">
            <h2><?=Yii::t('app', 'Sell faster')?></h2>
        </div>
        <!-- End Index image tilte  -->

        <!-- Index image Paragraph  -->
        <div class="index-image__paragraph">
            <p><?=\common\models\CMS::Block('Sell faster text')?></p>
        </div>
        <!-- End index image paragraph  -->

        <!-- Index Image button  -->
        <div class="index-image__button">
            <button class="btn btn--orange">
                <a href="<?=\yii\helpers\Url::to(['adv/add'])?>">
                    <span class="add-plus"><img src="<?=Yii::getAlias('@dist')?>/img/add.svg" alt="AddAds" class="svg"></span>
                    <span><?=Yii::t('app', 'Add adv')?></span>
                </a>
            </button>
        </div>
        <!-- End Index Image button  -->
    </div>
    <!--End Image Content  -->
</section>

<section class="about-us apps">


    <div class="about-us__bottom">

        <div class="about-bottom__left">

            <div class="bottom-left__text">
                <p>
                    <?=\common\models\CMS::Block('Main footer text')?>
                </p>
            </div>
        </div>


        <div class="about-bottom__right">

            <div class="bottom-right__apple">
                <a href="<?=Yii::$app->params['ios_app']?>" target="_blank">
                    <div class="about-btm__icon"><img src="<?=Yii::getAlias('@dist')?>/img/apple.png" alt="Apple Icon"></div>
                    <div class="about-apple__text"><?=Yii::t('app', "Upload <br /> in {name}", ['name' => 'Apple Store'])?></div>
                </a>
            </div>


            <div class="bottom-right__market">
                <a href="<?=Yii::$app->params['android_app']?>" target="_blank">
                    <div class="about-btm__icon"><img src="<?=Yii::getAlias('@dist')?>/img/market.png" alt="Google PlayMarket"></div>
                    <div class="about-market__text"><?=Yii::t('app', "Upload <br /> in {name}", ['name' => 'Google Play'])?></div>
                </a>
            </div>
        </div>

    </div>

</section>

<section class="news">

    <div class="sectionews-title">

        <h2><?=Yii::t('app', 'News and articles')?></h2>

        <a href="<?=\yii\helpers\Url::to(['news/index']) ?>"><span><?=Yii::t('app', 'All news')?></span><img src="<?=Yii::getAlias('@dist')?>/img/more.svg" class='svg' alt="<?=Yii::t('app', 'All news')?>"></a>

    </div>
    <!-- News Content  -->
    <div class="news-content">

        <?foreach ($last_news as $item):?>

            <!-- News Container  -->
            <div class="news-container">
                <a class='news-container__link' href="<?=$item->_link ?>">
                    <div class="news-container__image"><img src="<?=$item->path ?>" alt=""></div>

                    <div class="news-container__href"><?=$item->title?></div>

                    <div class="news-container__date" data-time="<?=$item->date ?>"></div>
                </a>
            </div>
            <!-- End News Container  -->
        <?endforeach;?>

    </div>
    <!-- End News Content  -->

</section>

<section class="often-search">

    <div class="often-search__title">
        <h2><?=Yii::t('app', 'Popular request')?></h2>
    </div>

    <div class="often-search__content">

        <?=\frontend\widgets\cms\PopularSearch::widget()?>

    </div>

</section>

<section class="about-us">
    <div class="about-us__title">

        <h2><?=Yii::t('app', 'About us')?></h2>

    </div>

    <div class="about-us__content">

        <div class="about-us__container">
            <p><?=\common\models\CMS::Block('About us 1')?></p>
        </div>


        <div class="about-us__container">
            <p><?=\common\models\CMS::Block('About us 2')?></p>
        </div>


        <div class="about-us__container">
            <p><?=\common\models\CMS::Block('About us 3')?> </p>
        </div>


        <div class="about-us__container">
            <p><?=\common\models\CMS::Block('About us 4')?></p>
        </div>


    </div>
</section>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use common\models\CMS;
use kosv\ulogin\widget\UloginWidget;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Login');
Yii::$app->breadcrumbs->Items([
    $this->title
]);
?>
<section class="content site-login">

    <div class="row">
        <div class="col-sm-6 col-sm-push-3">
            <h1><?= Html::encode($this->title) ?></h1>

            <div>
                <a v-show="login_type == 0" class="link"
                   @click="login_type = 1"><?= Yii::t('app', 'Login with phone') ?></a>
                <a v-show="login_type == 1" class="link"
                   @click="login_type = 0"><?= Yii::t('app', 'Login with email') ?></a>
<!--                --><?php //echo UloginWidget::widget([
//                'options' => [
//                    'display' => 'panel',
//                    'fields' => ['first_name', 'last_name', 'email', 'photo'],
//                    'providers' => ['google', 'facebook'],
////                    'callback' => 'authCallback', //Ваш js callback, который будет вызыватся для отправки данных в контроллер
//                    'redirect_uri' => \yii\helpers\Url::base('https').\yii\helpers\Url::to(['site/login-soc']) //При использовании callback, нужно поставить пустую строку
//                ],
//            ]);?>

                <div>
                    <a href="#modal-login" class="link" data-sideup><?=Yii::t('app', 'Entrance through social networks');?></a>
                </div>
            </div>

            <div v-show="login_type == 0" id="email-area">

                <?php $model = new \common\models\LoginForm();
                $form = ActiveForm::begin([
                    'id' => 'login-form',
                    'enableAjaxValidation' => true,
                    'action' => ['site/login'],
                    'validationUrl' => ['site/validate-login'],
                ]); ?>


                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput()->label(Yii::t('app', 'Password'). ' '. Html::a(Yii::t('app', 'Forgot password?'), ['site/request-password-reset'], ['class' => 'margin-left'])) ?>

                <div class="row">
                    <div class="col-sm-6"><?= Html::submitButton('<i class="icon icon-user" style="line-height: 17px; font-size: 21px;"></i>' . Yii::t('app', 'Login'), ['class' => 'btn btn--green btn--icon', 'enableClientValidation' => false]) ?></div>
                    <div class="col-sm-6" style="text-align: right"><a href="#modal-register" data-sideup class="btn btn--orange"><?=Yii::t('app', 'Registration');?> </a></div>
                </div>


                <?php ActiveForm::end(); ?>

            </div>
            <div v-show="login_type == 1" id="phone-area">

                <sms-login
                        codes='<?= json_encode(Yii::$app->params['sms_phone_codes']) ?>'
                        text_again="<?=Yii::t('app', 'Send code again');?>"
                        text_again_in="<?=Yii::t('app', 'Send code again in');?>"
                        text_send_code="<?=Yii::t('app', 'Send code');?>"
                        text_error="<?= Yii::t('app', 'Incorrect code'); ?>"
                        text_accept_code="<?=Yii::t('app', 'Accept code');?> "></sms-login>
            </div>
        </div>
    </div>
</section>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = Yii::t('app', 'Request password reset');
Yii::$app->breadcrumbs->Items([
    $this->title
]);
?>
<section class=" content site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p><?=Yii::t('app', 'Please fill out your email. A link to reset password will be sent there.');?> </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn--green']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</section>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/shutdown.php
<?php
/**
 * Created by PhpStorm.
 * User: York
 * Date: 24.03.2018
 * Time: 16:25
 */

$title = Yii::t('app', 'The site is now being updated');
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $title?></title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
    <link rel="stylesheet" href="/dist/css/main.min.css">
</head>
<body>
    <div class="row center-md center-sm margin-top">
        <div class="col-xs-12 col-sm-6 col-md-4">
            <h1> <?= $title?></h1>
            <p><?=Yii::t('app', 'We are preparing a new functional for you and soon it will be available.');?> </p>
        </div>
    </div>
    <div class="row center-md center-sm">
        <div class="col-xs-12 col-sm-8 col-md-8">
            <img src="/img/image.png" alt="" style="width: 100%">
        </div>
    </div>
</body>
</html>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'email') ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn--green', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</section>

frontend/views/site/test.php
<?
/* @var $this yii\web\View */

$this->registerJs("
$(\".owl-carousel1\").owlCarousel();
");

?>

<div class="owl-carousel1 owl-carousel" style="width: 600px">
    <? for ($i = 0; $i < 10; $i++): ?>
        <div><img src="/dist/img/noimage.jpg" alt="" style="width: 150px"></div>
    <? endfor; ?>
</div>